### ISSUE TITLE
Redesign the image and kernel ociClaim

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#309]
As per https://github.com/weaveworks/ignite/issues/298; we're gonna simplify

```yaml
spec:
  image:
    ociClaim:
      ref: weaveworks/ignite-ubuntu:latest
      type: Docker
```

to 

```yaml
spec:
  image:
    # Any image that is following the OCI specification is valid here.
    ociRef: weaveworks/ignite-ubuntu:latest
    # Reserve the possibility to add fields for other details
```

(and the same for `kernel`)

**Comment by twelho** [comment]
After some additional thought, we're going to further shorten `ociRef` to just `oci`, it's enough to signal the resource should be retrieved from the OCI implementation. So the target design looks like this:
```yaml
spec:
  image:
    # Any image that is following the OCI specification is valid here.
    oci: weaveworks/ignite-ubuntu:latest
    # Reserve the possibility to add fields for other details
```
