### ISSUE TITLE
Support ComponentConfig?

### ISSUE THREAD

**Issue by luxas** [weaveworks/ignite#315]
As `ignited` grows in complexity, instead of registering tons of flags on it, we'd use a declarative configuration file, aka. ComponentConfig, for it. (Could be even backed by git?)

**Comment by stealthybox** [comment]
Some defaults and values that could be configurable:
```yaml
- runtime
- network-plugin
- CNI subnet
- CNI options
- CNI network name
- docker network name
- dns.nameservers[]  (not implemented)
- dns.search[]  (not implemented)
- ipv6 support  (not implemented)
- vm.cpus
- vm.size
- vm.memory
- log-level
- kernel.image
- kernel.args
- gitops.repo-url
- gitops.branch / ref
- gitops.paths
```
These can be overridden by flags or the appropriate field in an Ignite VM API object.

**Comment by stealthybox** [comment]
Just brainstorming:
```shell
ignited daemon --config production-config.yaml
```
```yaml
apiVersion: ignite.weave.works/v1alpha1
kind: Configuration
metadata:
  name: production-config
spec:
  logLevel: debug
  runtime: docker
  networkPlugin: docker-bridge
  dockerBridge:
    network: testnet
  cni:
    subnet: 10.39.0.0/14
    networkName: prod-ignite-vm-bridge
    # options: 
  dns:
    # ipv6: true
    nameservers:
      - 1.1.1.1
      - 9.9.9.9
    search:
      - deployment.example.com
      - production.example.com
  gitops:
    repoURL: git@github.com/stealthybox/example
    ref: master
    paths:
      - ignite/production-backend
      - ignite/production-cache
  kernel:
    image: <something>
    cmdLine:
      - my
      - default
      - kernel
      - args
    vm:
      cpus: 4
      size: 20GB
      memory: 4GB
```

**Comment by stealthybox** [comment]
For the `ignite` tool since we do not yet have a complete daemon architecture, we could load this configuration file from some well known paths:

`/etc/ignite/runtime.yaml`
related XDG_CONFIG_HOME for root user?

**Comment by bbros-dev** [comment]
I'd say this belongs in XDG_DATA_HOME: `~/.local/share/ignite`, and the XDG_CONFIG_HOME would contain the much simpler configuration defaults such as:
```yaml
manifest:
  paths: 
    - /etc/firecracker/manifests
    - /dfs/db/firecracker/manifests
    - /dfs/sec/firecracker/manifests
    - /home/me/.local/share/ignite/manifests
    - /usr/local/share/ignite/manifests
    - /usr/share/ignite/manifests
```

What goes where?
 
- XDG_CONFIG_HOME: configuration that does **not** influence the specification/behaviour of the micro-VM
 - XDG_DATA_HOME: configuration that **does** influence the specification/behavior of the micro-VM
