### ISSUE TITLE
`ignite create --config` does not accept `v1alpha2` specifications

### ISSUE THREAD

**Issue by twelho** [weaveworks/ignite#322]
Running `ignite create --config conf.yml` where `conf.yml` contains
```yaml
apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  name: test-vm
  uid: fb733199f239a759
spec:
  image:
    oci: weaveworks/ignite-ubuntu
  cpus: 2
  diskSize: 3GB
  memory: 800MB
```
results in
`FATA[0000] unable to decode ignite.weave.works/v1alpha2, Kind=VM into *ignite.VM`.

Do you have an idea @luxas as to why this happens? `v1alpha2` is registered in the scheme.
