### ISSUE TITLE
Declarative port mappings and copy files values are getting cleared while CLI flags are empty

### ISSUE THREAD

**Issue by onatm** [weaveworks/ignite#795]
The title is self-explanatory but I should give more details.

I start an ignite VM using the below declarative configuration by executing `ignite run --config ubuntu.yaml`:

```yaml
apiVersion: ignite.weave.works/v1alpha3
kind: VM
metadata:
  name: ubuntu
spec:
  image:
    oci: weaveworks/ignite-ubuntu
  cpus: 1
  diskSize: 400MB
  memory: 64MB
  network:
    ports:
    - hostPort: 2222
      vmPort: 22
  ssh: true
``` 

When I run `ignite ps` I don't see any port mappings on the VM.

I've done some debugging and found where the issue is and it also showed me that `copyFiles` suffers the same problem.

Here's the offending line: https://github.com/weaveworks/ignite/blob/3120baf0e4f924a9280d59e7092fda3c57bcccb1/cmd/ignite/run/create.go#L221

I'll be creating a PR to fix this issue
