### ISSUE TITLE
Unknown Network Plugin "flannel"

### ISSUE THREAD

**Issue by MikePadge** [weaveworks/ignite#826]
Using the test script located here 
https://github.com/weaveworks/ignite/blob/main/tools/ignite-flannel.sh

I added flannel to my test host, but attempting to run ignite with the config fails

Note: I'm purposefully testing on debian with minimal configs to break things, if this is not helpful please let me know, and I can swap to Ubuntu
`Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
`
```
Ignite version: version.Info{Major:"0", Minor:"9", GitVersion:"v0.9.0", GitCommit:"e560f6242254868dfd92b7954866ba6f0f5779fc", GitTreeState:"clean", BuildDate:"2021-04-12T16:55:40Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64", SandboxImage:version.Image{Name:"weaveworks/ignite", Tag:"v0.9.0", Delimeter:":"}, KernelImage:version.Image{Name:"weaveworks/ignite-kernel", Tag:"5.4.108", Delimeter:":"}}
Firecracker version: v0.22.4
```

/etc/ignite/config.yaml

```
apiVersion: ignite.weave.works/v1alpha3
kind: Configuration
metadata:
  name: test-config
spec:
  runtime: containerd
  networkPlugin: flannel
```

/etc/cni/net.d/10-flannel.conflist

```
{
	"name": "cbr0",
	"cniVersion": "0.4.0",
	"plugins": [
		{
			"type": "flannel",
			"delegate": {
				"hairpinMode": true,
				"isDefaultGateway": true
			}
		},
		{
			"type": "portmap",
			"capabilities": {
				"portMappings": true
			}
		},
		{
			"type": "firewall"
		}
	]
}
```

**Comment by stealthybox** [comment]
Awesome that you're trying this out @MikePadge :+1:

The issue with your ignite config is that `flannel` isn't a valid ignite config string.
Ignite doesn't know anything specific about Flannel, only the general CNI interface.

Flannel is a CNI plugin so you want to configure ignite to call CNI (it already does this by default)
```
ignite run --help | grep network
      --network-plugin plugin             Network plugin to use. Available options are: [cni docker-bridge] (default cni)
```

So if you want to have an explicit runtime/network config, it should look like this:
```yaml
apiVersion: ignite.weave.works/v1alpha3
kind: Configuration
metadata:
  name: test-config
spec:
  runtime: containerd
  networkPlugin: cni    # change this :)
```

The associated guide for that script is [here](https://ignite.readthedocs.io/en/stable/networking/#multi-node-networking-with-flannel).
