### ISSUE TITLE
FATA[0000] unknown runtime ""   error on ignite stop/kill/attach

### ISSUE THREAD

**Issue by limegreendender2** [weaveworks/ignite#991]
I followed the install instructions and the last good command was
```
root@firecracker:/etc/firecracker/manifests# ignite ps
VM ID                                   IMAGE                           KERNEL                                  SIZE    CPUS    MEMORY   CREATED  STATUS          IPS     PORTS   NAME
0fd7d383-e547-4c59-918d-e238100f6ff6    weaveworks/ignite-ubuntu:latest weaveworks/ignite-kernel:5.10.51        3.0 GB  2       800.0 MB 3d ago   Up <nil>                        smoke-test
```
Unfortunately the attach and subsequent commands fail.
```
root@firecracker:/etc/firecracker/manifests#  ignite attach smoke-test
FATA[0000] unknown runtime ""     
```
Ignite version
```
root@firecracker:/etc/firecracker/manifests# ignite version
Ignite version: version.Info{Major:"0", Minor:"10", GitVersion:"v0.10.0", GitCommit:"4540abeb9ba6daba32a72ef2b799095c71ebacb0", GitTreeState:"clean", BuildDate:"2021-07-19T20:52:59Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64", SandboxImage:version.Image{Name:"weaveworks/ignite", Tag:"v0.10.0", Delimeter:":"}, KernelImage:version.Image{Name:"weaveworks/ignite-kernel", Tag:"5.10.51", Delimeter:":"}}
Firecracker version: v0.22.4

root@firecracker:~# lscpu | grep Virtualization
Virtualization:                  AMD-V

root@firecracker:~# lsmod | grep kvm
kvm_amd               151552  12
kvm                  1019904  1 kvm_amd
ccp                    98304  1 kvm_amd
irqbypass              16384  12 vfio_pci_core,kvm

root@firecracker:~# containerd --version
containerd containerd.io 1.6.18 2456e983eb9e37e47538f59ea18f2043c9a73640
```
I've tried this on two environments - both with the same results
WSL2 with KVM enabled kernel
and
Debian Bullseye with kernel 5.15.74-1-pve running under proxmox.

strace prior to error message

```
[pid  3630] newfstatat(AT_FDCWD, "/var/lib/firecracker/vm/0fd7d383-e547-4c59-918d-e238100f6ff6/metadata.json", {st_mode=S_IFREG|0644, st_size=917, ...}, 0) = 0
[pid  3630] openat(AT_FDCWD, "/var/lib/firecracker/vm/0fd7d383-e547-4c59-918d-e238100f6ff6/metadata.json", O_RDONLY|O_CLOEXEC) = 7
[pid  3630] epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=465838016, u64=140145248706496}}) = -1 EPERM (Operation not permitted)
[pid  3630] epoll_ctl(4, EPOLL_CTL_DEL, 7, 0xc0001df33c) = -1 EPERM (Operation not permitted)
[pid  3630] fstat(7, {st_mode=S_IFREG|0644, st_size=917, ...}) = 0
[pid  3630] read(7, "{\n  \"kind\": \"VM\",\n  \"apiVersion\""..., 918) = 917
[pid  3630] read(7, "", 1)              = 0
[pid  3630] close(7)                    = 0
[pid  3630] openat(AT_FDCWD, "/var/lib/firecracker/vm/0fd7d383-e547-4c59-918d-e238100f6ff6/metadata.json", O_RDONLY|O_CLOEXEC) = 7
[pid  3630] epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=465838016, u64=140145248706496}}) = -1 EPERM (Operation not permitted)
[pid  3630] epoll_ctl(4, EPOLL_CTL_DEL, 7, 0xc0001df61c) = -1 EPERM (Operation not permitted)
[pid  3630] fstat(7, {st_mode=S_IFREG|0644, st_size=917, ...}) = 0
[pid  3630] read(7, "{\n  \"kind\": \"VM\",\n  \"apiVersion\""..., 918) = 917
[pid  3630] read(7, "", 1)              = 0
[pid  3630] close(7)                    = 0
[pid  3630] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f761b8c3000
[pid  3630] newfstatat(AT_FDCWD, "/var/lib/firecracker/vm/0fd7d383-e547-4c59-918d-e238100f6ff6/metadata.json", {st_mode=S_IFREG|0644, st_size=917, ...}, 0) = 0
[pid  3630] newfstatat(AT_FDCWD, "/var/lib/firecracker/vm/0fd7d383-e547-4c59-918d-e238100f6ff6/metadata.json", {st_mode=S_IFREG|0644, st_size=917, ...}, 0) = 0
[pid  3630] ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  3630] write(1, "\33[31mFATA\33[0m[0000] unknown runt"..., 66FATA[0000] unknown runtime ""     
```

**Comment by woodliu** [comment]
@limegreendender2 Hi, could you post the file content of `/etc/firecracker/manifests/smoke-test.yml` on the machine?
And show the command result:
`ctr --namespace firecracker container ls`
`ctr --namespace firecracker task ls`
You can use `ctr --namespace firecracker task attach ignite-xxxx` attach the vm as well.

**Comment by limegreendender2** [comment]
```
apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  created: "2023-08-04T13:43:10Z"
  name: smoke-test
  uid: 0fd7d383-e547-4c59-918d-e238100f6ff6
spec:
  cpus: 2
  diskSize: 3GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:5.10.51
  memory: 800MB
  network: {}
  sandbox:
    oci: weaveworks/ignite:v0.10.0
  storage: {}
status:
  idPrefix: ""
  image:
    id: null
    size: 0B
  kernel:
    id: null
    size: 0B
  network:
    ipAddresses: null
    plugin: ""
  running: true
  runtime:
    id: ""
    name: ""

root@firecracker:~# ctr --namespace firecracker container ls
CONTAINER    IMAGE    RUNTIME  

root@firecracker:~# ctr --namespace firecracker task ls
TASK    PID    STATUS  

root@firecracker:~# ignite ps
VM ID                                   IMAGE                           KERNEL                                  SIZE    CPUS    MEMORY          CREATED         STATUS          IPS     PORTS   NAME
0fd7d383-e547-4c59-918d-e238100f6ff6    weaveworks/ignite-ubuntu:latest weaveworks/ignite-kernel:5.10.51        3.0 GB  2       800.0 MB        3d18h ago       Up <nil>                        smoke-test

```

**Comment by woodliu** [comment]
@limegreendender2 Hi, there actually some bugs with `ignite rm`, i will fix that later, for now, you can clean the env and restart the vm:

1. use `pe -ef|grep ignited` to find the PID of ignited, and  use `kill`  command to stop it
2. use `ignite vm stop ignite-xxx`  and `ignite vm rm ignite-xxx`   the clean the ignite vm
3. `cd /etc/firecracker/manifests/` and  `rm smoke-test.yml`
4. run` ignited daemon --log-level debug &` to restart the ignited daemon
5. recreate vm manifest file, and then 
```
VMFILE=/etc/firecracker/manifests/smoke-test.yml
tee "$VMFILE" > /dev/null <<EOF
apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  name: smoke-test
  uid: $(uuidgen)
spec:
  image:
    oci: weaveworks/ignite-ubuntu
  cpus: 2
  diskSize: 3GB
  memory: 800MB
  ssh:
    generate: true
status:
  running: true
EOF
```

And then run 
`ctr --namespace firecracker container ls` and `ctr --namespace firecracker task ls` to check if the contianerd contaier been created.
